#-------------------------------
# General Site Settings

title: Sonja Olson!
description: Thinker // Designer // Programmer
email: olson1sonja@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Resume, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Women computer science engineer in Portland Oregon'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  Creative code manipulator by day, lens capturer by night. Based out of Portland, OR.

#-------------------------------
# Work Section

projects:
- {name: Software Engineer, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Freelance photographer, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Freelance Videographer, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Web Developer, folder: 'proj-4', file: 'work/proj-4.html'}





#-------------------------------
# Clients Section



#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: ''}
- {icon: 'youtube', link: ''}
- {icon: 'linkedin', link: ''}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
